alwaysConsumeRune: true
socketSpaceLore: "&6(Socket)"
replaceRuneWithSocket: true
failChance: 30
limitToWeapons: true
geometricEvolution: true
geometricFactor: 2
sendMoneyMessage: true
runeText: "Rune of Protection"
levelCaps:
  ARROW_DAMAGE: 10
  ARROW_FIRE: 10
  ARROW_INFINITE: 1
  ARROW_KNOCKBACK: 10
  DAMAGE_ALL: 10
  DAMAGE_ARTHROPODS: 10
  DAMAGE_UNDEAD: 10
  DEPTH_STRIDER: 10
  DIG_SPEED: 10
  DURABILITY: 10
  FIRE_ASPECT: 10
  FROST_WALKER: 10
  KNOCKBACK: 10
  LOOT_BONUS_BLOCKS: 10
  LOOT_BONUS_MOBS: 10
  LUCK: 10
  LURE: 10
  MENDING: 10
  OXYGEN: 10
  PROTECTION_ENVIRONMENTAL: 10
  PROTECTION_EXPLOSIONS: 10
  PROTECTION_FALL: 10
  PROTECTION_FIRE: 10
  PROTECTION_PROJECTILE: 10
  SILK_TOUCH: 10
  THORNS: 10
  WATER_WORKER: 10
prices:
  ARROW_DAMAGE: 100
  ARROW_FIRE: 300
  ARROW_INFINITE: 300
  ARROW_KNOCKBACK: 300
  DAMAGE_ALL: 300
  DAMAGE_ARTHROPODS: 300
  DAMAGE_UNDEAD: 300
  DEPTH_STRIDER: 300
  DIG_SPEED: 300
  DURABILITY: 300
  FIRE_ASPECT: 300
  FROST_WALKER: 300
  KNOCKBACK: 300
  LOOT_BONUS_BLOCKS: 300
  LOOT_BONUS_MOBS: 300
  LUCK: 300
  LURE: 300
  MENDING: 300
  OXYGEN: 300
  PROTECTION_ENVIRONMENTAL: 300
  PROTECTION_EXPLOSIONS: 300
  PROTECTION_FALL: 300
  PROTECTION_FIRE: 300
  PROTECTION_PROJECTILE: 300
  SILK_TOUCH: 300
  THORNS: 300
  WATER_WORKER: 300